# Generated by Django 5.2.1 on 2025-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
