# Generated by Django 5.2.1 on 2025-08-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_searchhistory_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.product'),
        ),
    ]
