# Generated by Django 5.2.1 on 2025-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_alter_cartorderitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
