# Generated by Django 5.2.1 on 2025-06-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
