# Generated by Django 5.2.1 on 2025-08-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_alter_cartorderitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.product'),
        ),
    ]
