# Generated by Django 5.2.1 on 2025-06-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('', 'None')], default='processing', max_length=20),
        ),
    ]
