# Generated by Django 5.2.1 on 2025-06-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_alter_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('', 'None')], default='null', max_length=200),
        ),
    ]
