# Generated by Django 5.2.1 on 2025-06-23 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0013_recentlyvieweditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
