# Generated by Django 5.2.1 on 2025-06-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0015_remove_product_viewed_at_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='recently_viewed/'),
        ),
        migrations.DeleteModel(
            name='RecentlyViewedItem',
        ),
    ]
