# Generated by Django 5.2.1 on 2025-06-24 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0016_productview_product_image_delete_recentlyvieweditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='productview',
            unique_together={('user', 'product')},
        ),
    ]
