# Generated by Django 5.2.1 on 2025-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
